### ISSUE TITLE
A clear all feature ? A on click/ command to clear all drawing done

### ISSUE THREAD

**Issue by TreavVasu** [Apostolique/Mitten#15]
I can help to contribute in the issue 
Just let me know where is the function we need to dealt with is

**Comment by Apostolique** [comment]
Been busy, sorry for responding so late. The main code to look at would be https://github.com/Apostolique/Mitten/blob/87939af3a36a3b4ac348f66d9c4d7cc10fe6b7f1/Game/GameRoot.cs#L571-L690

I wonder if this should be handled by undoing everything instead of actually deleting. The hotkey should be hard to hit accidentally.

"Total Undo" could be done with a while loop such as `while (_undoGroups.Count > 0) {`.

**Comment by Apostolique** [comment]
I added this in version 2.1.0. You can access it with `Ctrl + Backspace` and `Ctrl + Shift + Backspace`.

Note that just like when Undoing, if you undo everything and then draw, all your work will be lost. A backup system might be nice.

**Comment by TreavVasu** [comment]
Thanks 
I would look If I could pick up the saving one

**Comment by Apostolique** [comment]
What do you mean?
